"""create initial tables

Revision ID: 38a00389714e
Revises: 
Create Date: 2025-09-08 11:42:01.246256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a00389714e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_snapshot', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('order_reference', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_order_reference'), 'orders', ['order_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_reference'), table_name='orders')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'order_reference')
    op.drop_column('order_items', 'product_snapshot')
    # ### end Alembic commands ###
