"""Initial migration

Revision ID: f8787cff56c2
Revises: c50e84452f66
Create Date: 2025-09-11 10:25:14.142985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8787cff56c2'
down_revision: Union[str, None] = 'c50e84452f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'payment_options', ['payment_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_option_id')
    # ### end Alembic commands ###
